name: "check flake"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        profile:
          - default
          - neovim
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@v4
      - run: nix develop -c just check

  package:
    needs:
      - check
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        profile:
          - default
          - neovim
    runs-on: ${{ matrix.os }}
    steps:

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@v4
      - run: nix develop -c just package "${{ matrix.profile }}"
